// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFKhcTrNX8DLmuQ8WibXdPbjEMqK_ufMQ',
    appId: '1:598956986415:web:3a864f5833f9d5b30876da',
    messagingSenderId: '598956986415',
    projectId: 'samplereels',
    authDomain: 'samplereels.firebaseapp.com',
    storageBucket: 'samplereels.firebasestorage.app',
    measurementId: 'G-795J42WH2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRCvnlivITv60HbIBrVcoPPNC1b9j2NEY',
    appId: '1:598956986415:android:7b5e823606578d940876da',
    messagingSenderId: '598956986415',
    projectId: 'samplereels',
    storageBucket: 'samplereels.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBufGn7BlmsAT_bEZVwL4j9YCtk1WTpJfc',
    appId: '1:598956986415:ios:33b71518eba11a120876da',
    messagingSenderId: '598956986415',
    projectId: 'samplereels',
    storageBucket: 'samplereels.firebasestorage.app',
    iosBundleId: 'com.example.sampleReels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBufGn7BlmsAT_bEZVwL4j9YCtk1WTpJfc',
    appId: '1:598956986415:ios:33b71518eba11a120876da',
    messagingSenderId: '598956986415',
    projectId: 'samplereels',
    storageBucket: 'samplereels.firebasestorage.app',
    iosBundleId: 'com.example.sampleReels',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFKhcTrNX8DLmuQ8WibXdPbjEMqK_ufMQ',
    appId: '1:598956986415:web:367f4e2c98f6c5270876da',
    messagingSenderId: '598956986415',
    projectId: 'samplereels',
    authDomain: 'samplereels.firebaseapp.com',
    storageBucket: 'samplereels.firebasestorage.app',
    measurementId: 'G-57D1XFTQGS',
  );
}
